### ISSUE TITLE
Comments before JSX prevent rendering

### ISSUE THREAD

**Issue by esturcke** [philpl/react-live#4]
I was playing around with the live demo and it looks like nothing gets rendered when a comment precedes the JSX:

```jsx
// a comment
<h3>
  Hello World!
</h3>
```

**Comment by philpl** [comment]
Thanks for reporting :smile: What a peculiar bug!

I'm doing the buble transpilation with the inline code btw, so that the error messages don't need to be reformatted. And I made a mistake that makes things like these fail. Oops

Should work now:

https://github.com/philpl/react-live/commit/d49895a

Also added a test to prevent future regressions

**Comment by esturcke** [comment]
Update my project and it works beautifully.
